### ISSUE TITLE
ComfyUi node has been updated (stages split out) so need new workflow at least....

### ISSUE THREAD

**Issue by CCpt5** [Nestorchik/ComfyUI-SUPIR-BAT#1]
Hi!

I cannot speak to installation, but I was looking for a simple workflow to use the ComfyUI node for SUPIR. Since a day or so the latest update splits the single node into multiple (SUPIR encode / decode / etc). If you update (git pull) and then try the .json you provide you'll see that the comfy node shows as red-missing.  It will need to be updated for the new split apart format (which lets you skip stage 1 and/or do other manipulations).

Just wanted to give you a heads-up on that - and if you make an updated simple workflow that would help non-expert comfy users like myself :)

(I did switch to development branch for a minute yesterday, but I'm pretty sure the main branch is split now too - if not it will be very soon: https://github.com/kijai/ComfyUI-SUPIR/commit/b1d163957548f57dab1320d2ef733c90eeee2134)

**Comment by Nestorchik** [comment]
Okay, I'll check everything now.

**Comment by Nestorchik** [comment]
I am following the changes on GIT, if something changes, I will update this repository.
![image](https://github.com/Nestorchik/ComfyUI-SUPIR-BAT/assets/74113797/f7f4bbb3-7f2b-4ec1-adf1-83a152b98757)

**Comment by Nestorchik** [comment]
I just tested it, the git versions are fresh. Everything is working fine. I don't see any problems.

**Comment by Nestorchik** [comment]
Thanks for the warning.
I have included more lines in the installation file:
echo ==================================
echo File "examples\supir_workflow.json" only for "SUPIR_Upacaler" node version "v1"!
echo After updating the node to version "v2" (installation is done with "git"!), this file may work unpredictably!
echo ==================================

**Comment by Nestorchik** [comment]
Supir today updated to v.2
All OK
